export async function generateImageCaption(imageFile: File): Promise<string> {
  // Simulate AI caption generation
  // In a real app, you would use the AI SDK with a vision model

  const captions = [
    "A beautiful landscape with mountains and trees in the background.",
    "A group of friends enjoying a meal together at a restaurant.",
    "A stunning sunset over the ocean with vibrant colors in the sky.",
    "A cozy indoor scene with warm lighting and comfortable furniture.",
    "An architectural detail showing modern design elements.",
    "A close-up shot with interesting textures and patterns.",
    "A street scene capturing everyday life in the city.",
    "A nature photograph showcasing the beauty of the outdoors.",
    "An artistic composition with creative use of light and shadow.",
    "A candid moment capturing genuine emotions and expressions.",
  ]

  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1500 + Math.random() * 1000))

  // Return a random caption (in real app, this would be generated by AI)
  return captions[Math.floor(Math.random() * captions.length)]
}
